# Generated by Django 3.2.6 on 2021-08-18 12:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, default='users/default.png', upload_to=users.models.upload_to, verbose_name='UserImage'),
        ),
    ]
