# Generated by Django 3.2.6 on 2021-08-18 12:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, default='users/default.jpg', upload_to=users.models.upload_to, verbose_name='UserImage'),
        ),
    ]
