# Generated by Django 3.2.6 on 2021-08-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210818_2129'),
        ('users', '0006_remove_customuser_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commmented',
            field=models.ManyToManyField(blank=True, related_name='commented_on_posts', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='blog.Post'),
        ),
    ]
