# Generated by Django 3.2.6 on 2021-08-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210818_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='commmented',
            new_name='commmented_on',
        ),
    ]
