# Generated by Django 3.2.6 on 2021-08-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210821_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='commented_on',
        ),
    ]
