# Generated by Django 3.2.6 on 2021-08-18 13:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(default='users/default.jpg', null=True, upload_to=users.models.upload_to, verbose_name='UserImage'),
        ),
    ]
