# Generated by Django 3.2.6 on 2021-08-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_image',
        ),
    ]
