# Generated by Django 3.2.6 on 2021-08-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210819_1639'),
        ('users', '0008_rename_commmented_customuser_commmented_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarked_posts', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='commmented_on',
            field=models.ManyToManyField(blank=True, null=True, related_name='commented_on_posts', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked_posts', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_posts', to='blog.Post'),
        ),
    ]
